# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Article_image',
            field=models.ImageField(default='img', upload_to='img', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Article_text',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Article_url',
            field=models.CharField(max_length=300, verbose_name='链接'),
        ),
    ]
