# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170313_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Article_image',
            field=models.ImageField(upload_to='img', verbose_name='图片'),
        ),
    ]
