# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20170313_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Article_image',
        ),
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='图片地址'),
            preserve_default=False,
        ),
    ]
